#!/bin/bash

if [ $1 ] ; then
    case $1 in
        up)
            sudo ifconfig wlan0 192.168.42.1 up
            sudo service firestarter start 
            sudo service hostapd start
            sudo service isc-dhcp-server start
        ;;
        down)
            sudo ifconfig wlan0 down
            sudo service firestarter stop 
            sudo service hostapd stop
            sudo service isc-dhcp-server stop
        ;;
        setup)
            sudo rmmod acer_wmi
            sudo modprobe acer_wmi
            sudo rfkill unblock all
            sudo rmmod -f acer_wmi
        ;;
    esac
else
    echo "Usage:"
    echo "  wifi up    - create ad-hoc."
    echo "  wifi ap    - create access point."
    echo "  wifi down  - stop all."       
    echo "  wifi setup - b570e quickfix."       
fi

