#!/bin/bash
# Вкл/выкл точку типа ad-hoc.

if [ $1 ] ; then
    case $1 in
        -u)
            sudo iwconfig wlan0 mode Ad-Hoc
            sudo iwconfig wlan0 channel 4
            sudo iwconfig wlan0 essid NW
            sudo ifconfig wlan0 up 192.168.0.1
            sudo firestarter --start-hidden > /dev/null &
        ;;
        -d)
            sudo ifconfig wlan0 down
            sudo killall -9 firestarter > /dev/null
        ;;
    esac
else
    echo "Usage:"
    echo "  wifi -d : create ad-hoc."
    echo "  wifi -u : remove ad-hoc."       
fi
