#!/bin/bash
# Push all files at right places.

for dotfile in `ls`
do
    if [ $dotfile == `basename $0` -o \
         $dotfile == "README.md" ]; then
        false

    elif [ $dotfile == "config" ]; then
        if ! [ -d "${HOME}/.config" ]; then 
            mkdir "${HOME}/.config" 
        fi
        for config in `ls config`; do
            rm -rf "${HOME}/.config/${config}"
            ln -s "${PWD}/config/${config}" "${HOME}/.config/${config}"
        done

    else
        rm -rf "${HOME}/.${dotfile}"
        ln -s "${PWD}/$dotfile" "${HOME}/.$dotfile"
    fi
done
