#!/bin/bash
# Push all files at right places.

for dotfile in `ls`
do
    if [ $dotfile == `basename $0` -o \
         $dotfile == "README.md" ]; then
        false

    else
        rm -rf "${HOME}/.${dotfile}"
        ln -s "${PWD}/$dotfile" "${HOME}/.$dotfile"
    fi
done
