#!/bin/sh

setxkbmap -layout 'us,ru' -option 'grp:alt_shift_toggle'
setxkbmap -layout 'us,ru' -option 'grp:alt_space_toggle'
setxkbmap -option caps:escape
xinput --set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput --set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput --set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
xinput --set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
