#!/bin/bash

LEFT='HDMI1'
RIGHT='VGA1'

gotscreen()
{
	xrandr | grep ' connected ' | cut -d' ' -f1 | grep $1 > /dev/null \
		&& echo true
}

setxkbmap -layout 'us,ru' -option 'grp:alt_space_toggle'
setxkbmap -option caps:escape
if [[ $(gotscreen $LEFT) == 'true' ]] && [[ $(gotscreen $RIGHT) == 'true' ]]; then
	xrandr --output $LEFT --auto --primary --output $RIGHT --auto --right-of $LEFT
fi

