general {
    lock_cmd = pidof hyprlock || hyprlock
    on_lock_cmd = ~/.config/hypr/scripts/hypridle-hook lock-dpms-off
}

listener {
    timeout = 600
    on-timeout = ~/.config/hypr/scripts/hypridle-hook dpms-off
    on-resume = ~/.config/hypr/scripts/hypridle-hook dpms-on
}

listener {
    timeout = 620
    on-timeout = ~/.config/hypr/scripts/hypridle-hook lock
}

listener {
    timeout = 3600
    on-timeout = ~/.config/hypr/scripts/hypridle-hook suspend
}
